
on:
  push:
    tags:
      - '*'
jobs:
  build_and_push:
    name: "Build and push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Make tag
        id: make_tag
        run: echo ::set-output name=TAG::$(echo ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }})

      - name: Login to base-reg 
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.DOCKER_BASE_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t ${{ steps.make_tag.outputs.TAG }} .

      - name: Login to img-reg 
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        uses: actions-hub/docker@master
        with:
          args: push ${{ steps.make_tag.outputs.TAG }}

